global:
  scrape_interval: 15s
  external_labels:
    monitor: 'link-tracker-monitor'

scrape_configs:
  - job_name: 'scrapper job'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8081']
        labels:
          group: 'scrapper'

  - job_name: 'bot job'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:8091' ]
        labels:
          group: 'bot'
