app:
  topic:
    name: "topic1"
    partitions-count: 1
    replicas-count: 2
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jdbc
  use-queue: true

third-party-web-clients:
  github-properties:
    timeout-in-milliseconds: 1000
    base-url: https://api.github.com/
  stackoverflow-properties:
    timeout-in-milliseconds: 1000
    base-url: https://api.stackexchange.com/2.3/

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        connection:
          driver_class: org.postgresql.Driver
        hbm2ddl:
          auto: validate
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
