app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jpa

third-party-web-clients:
  github-properties:
    timeout-in-milliseconds: 1000
    base-url: https://api.github.com/repos/
  stackoverflow-properties:
    timeout-in-milliseconds: 1000
    base-url: https://api.stackexchange.com/2.3/questions/

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        connection:
          driver_class: org.postgresql.Driver
        hbm2ddl:
          auto: validate

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
