app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 60s
  github-client-settings:
    timeout-in-milliseconds: 1000
  stackoverflow-client-settings:
    timeout-in-milliseconds: 1000

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/scrapper
          username: postgres
          password: postgres
        hbm2ddl:
          auto: validate

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
