app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-topic:
    name: "topic1"
    partitions-count: 1
    replicas-count: 2

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
