app:
  telegram-token: ${TELEGRAM_TOKEN}
  kafka-topic-name: "topic1"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
