app:
  telegram-token: ${TELEGRAM_TOKEN}
  kafka-settings:
    enabled: true
    consumer-group-id: 'consumer-group-1'
    topics:
      scrapper-topic:
        enabled: true
        name: "topic1"
        partitions-count: 1
        replicas-count: 2
      dead-letter-queue-topic:
        enabled: true
        name: "faulty_dlq"
        partitions-count: 1
        replicas-count: 2

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
